// Alerts
export const ALERT_SET = 'ALERT_SET';
export const ALERT_REMOVE = 'ALERT_REMOVE';
export const ALERT_RESET = 'ALERT_RESET';

// Register & Log In
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Profiles Page
export const PROFILE_LOAD_PAGE_REQUEST = 'PROFILE_LOAD_PAGE_REQUEST';
export const PROFILE_LOAD_PAGE_SUCCESS = 'PROFILE_LOAD_PAGE_SUCCESS';
export const PROFILE_LOAD_PAGE_FAIL = 'PROFILE_LOAD_PAGE_FAIL';
export const PROFILE_LOAD_PAGE_RESET = 'PROFILE_LOAD_PAGE_RESET';

// Load single profile page
export const PROFILE_LOAD_SINGLE_SUCCESS = 'PROFILE_LOAD_SINGLE_SUCCESS';
export const PROFILE_LOAD_SINGLE_FAIL = 'PROFILE_LOAD_SINGLE_FAIL';
export const PROFILE_LOAD_SINGLE_RESET = 'PROFILE_LOAD_SINGLE_RESET';

// Load single profile github repositories
export const PROFILE_LOAD_REPOS_SUCCESS = 'PROFILE_LOAD_REPOS_SUCCESS';
export const PROFILE_LOAD_REPOS_FAIL = 'PROFILE_LOAD_REPOS_FAIL';
export const PROFILE_LOAD_REPOS_RESET = 'PROFILE_LOAD_REPOS_RESET';

// Create/Update Profile for current user
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';

// Get currently logged in user profile
export const PROFILE_LOAD_CURRENT_SUCCESS = 'PROFILE_LOAD_CURRENT_SUCCESS';
export const PROFILE_LOAD_CURRENT_FAIL = 'PROFILE_LOAD_CURRENT_FAIL';

// Delete currently logged in user profile's education
export const PROFILE_DELETE_CURRENT_EDUCATION_SUCCESS =
  'PROFILE_DELETE_CURRENT_EDUCATION_SUCCESS';
export const PROFILE_DELETE_CURRENT_EDUCATION_FAIL =
  'PROFILE_DELETE_CURRENT_EDUCATION_FAIL';

// Delete currently logged in user profile's experience
export const PROFILE_DELETE_CURRENT_EXPERIENCE_SUCCESS =
  'PROFILE_DELETE_CURRENT_EXPERIENCE_SUCCESS';
export const PROFILE_DELETE_CURRENT_EXPERIENCE_FAIL =
  'PROFILE_DELETE_CURRENT_EXPERIENCE_FAIL';

// Add education to currently logged in user profile
export const PROFILE_ADD_EDUCATION_SUCCESS = 'PROFILE_ADD_EDUCATION_SUCCESS';
export const PROFILE_ADD_EDUCATION_FAIL = 'PROFILE_ADD_EDUCATION_FAIL';

// Add experience to currently logged in user profile
export const PROFILE_ADD_EXPERIENCE_SUCCESS = 'PROFILE_ADD_EXPERIENCE_SUCCESS';
export const PROFILE_ADD_EXPERIENCE_FAIL = 'PROFILE_ADD_EXPERIENCE_FAIL';

// Delete current profile and user
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';
